[package]
name = "skippy-cache"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Cache primitives for Skippy staged runtime serving"
repository = "https://github.com/Mesh-LLM/mesh-llm"
homepage = "https://github.com/Mesh-LLM/mesh-llm"

[lib]
name = "skippy_cache"
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
blake3.workspace = true
fs2 = "0.4"
libc = "0.2.183"
serde.workspace = true
serde_json.workspace = true
skippy-protocol = { path = "../skippy-protocol", version = "0.76.0-rc9"  }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_Storage_FileSystem",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
] }
