event_family!(RequestEventKind {
    RequestReceived => "request_received",
    RequestQueued => "request_queued",
    RequestAdmitted => "request_admitted",
    RequestRejected => "request_rejected",
    RequestExecutionStarted => "request_execution_started",
    RequestCompleted => "request_completed",
    RequestCancelled => "request_cancelled",
    RequestTimedOut => "request_timed_out",
    RequestFailed => "request_failed",
});

event_family!(PrefillEventKind {
    PromptProcessingStarted => "prompt_processing_started",
    TokenizationCompleted => "tokenization_completed",
    TokenizationFailed => "tokenization_failed",
    PrefillStarted => "prefill_started",
    PrefillProgress => "prefill_progress",
    PrefillCompleted => "prefill_completed",
    PrefillCancelled => "prefill_cancelled",
    PrefillFailed => "prefill_failed",
    MediaPrefillStarted => "media_prefill_started",
    MediaPrefillCompleted => "media_prefill_completed",
    MediaPrefillFailed => "media_prefill_failed",
    PromptCacheRestoreHit => "prompt_cache_restore_hit",
    PromptCacheRestoreMiss => "prompt_cache_restore_miss",
    PromptCacheRestorePartial => "prompt_cache_restore_partial",
    PromptCacheRestoreError => "prompt_cache_restore_error",
});

event_family!(GenerationEventKind {
    GenerationStarted => "generation_started",
    FirstTokenProduced => "first_token_produced",
    GenerationProgress => "generation_progress",
    GenerationCompleted => "generation_completed",
    GenerationCancelled => "generation_cancelled",
    GenerationTimedOut => "generation_timed_out",
    GenerationFailed => "generation_failed",
    StopConditionReached => "stop_condition_reached",
});

event_family!(KvRuntimeStateEventKind {
    KvCacheInitializationStarted => "kv_cache_initialization_started",
    KvCacheInitializationCompleted => "kv_cache_initialization_completed",
    KvCacheInitializationFailed => "kv_cache_initialization_failed",
    CacheLookupHit => "cache_lookup_hit",
    CacheLookupMiss => "cache_lookup_miss",
    CacheLookupPartial => "cache_lookup_partial",
    CacheLookupError => "cache_lookup_error",
    PrefixRestored => "prefix_restored",
    CheckpointRestored => "checkpoint_restored",
    CacheRecordCompleted => "cache_record_completed",
    CacheRecordFailed => "cache_record_failed",
    CacheTrim => "cache_trim",
    CacheEviction => "cache_eviction",
    CacheReset => "cache_reset",
    CachePressureCrossed => "cache_pressure_crossed",
    CachePressureCleared => "cache_pressure_cleared",
    ContextCapacityApproachingLimit => "context_capacity_approaching_limit",
    ContextExhausted => "context_exhausted",
    RuntimeStateImportCompleted => "runtime_state_import_completed",
    RuntimeStateImportFailed => "runtime_state_import_failed",
    RuntimeStateExportCompleted => "runtime_state_export_completed",
    RuntimeStateExportFailed => "runtime_state_export_failed",
});

event_family!(ResourceHealthEventKind {
    BackendInitializationStarted => "backend_initialization_started",
    BackendInitializationCompleted => "backend_initialization_completed",
    BackendInitializationFailed => "backend_initialization_failed",
    DeviceSelected => "device_selected",
    DeviceReady => "device_ready",
    DeviceDegraded => "device_degraded",
    DeviceUnavailable => "device_unavailable",
    DeviceRecovered => "device_recovered",
    ResourceAllocationCompleted => "resource_allocation_completed",
    ResourceAllocationFailed => "resource_allocation_failed",
    MemoryPressureCrossed => "memory_pressure_crossed",
    MemoryPressureCleared => "memory_pressure_cleared",
    OutOfMemoryCondition => "out_of_memory_condition",
    BackendFallbackActivated => "backend_fallback_activated",
    CpuFallbackActivated => "cpu_fallback_activated",
    ComputeFailure => "compute_failure",
    DeviceLost => "device_lost",
    DeviceReset => "device_reset",
});

event_family!(DiagnosticEventKind {
    WarningRaised => "warning_raised",
    WarningCleared => "warning_cleared",
    RecoverableNativeFailure => "recoverable_native_failure",
    FallbackApplied => "fallback_applied",
    DegradedOperationEntered => "degraded_operation_entered",
    DegradedOperationExited => "degraded_operation_exited",
    FatalNativeFailure => "fatal_native_failure",
    InvariantProtocolViolation => "invariant_protocol_violation",
});

event_family!(NodeAvailabilityEventKind {
    NodeStarting => "node_starting",
    NodeAcceptingRequests => "node_accepting_requests",
    NodeDegraded => "node_degraded",
    NodeUnavailable => "node_unavailable",
    NodeDraining => "node_draining",
    NodeStopped => "node_stopped",
    AvailableModelSetChanged => "available_model_set_changed",
    AvailableStageSetChanged => "available_stage_set_changed",
    RequestCapacityChanged => "request_capacity_changed",
    LaneCapacityChanged => "lane_capacity_changed",
    SessionCapacityChanged => "session_capacity_changed",
    ResourcePressureChanged => "resource_pressure_changed",
});

event_family!(EventSystemHealthEventKind {
    IngressQueuePressure => "ingress_queue_pressure",
    EventsCoalesced => "events_coalesced",
    EventsSampled => "events_sampled",
    EventsDroppedByClass => "events_dropped_by_class",
    SubscriberLagging => "subscriber_lagging",
    SubscriberDisconnected => "subscriber_disconnected",
    ReducerError => "reducer_error",
    TelemetryExporterDegraded => "telemetry_exporter_degraded",
    TelemetryExporterRecovered => "telemetry_exporter_recovered",
    EventSchemaIncompatibility => "event_schema_incompatibility",
    UnknownNativeEventReceived => "unknown_native_event_received",
});
