#!/usr/bin/env python3
"""Generate the deterministic llama.cpp model-family stage-control patch."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile


PATCH_HEADER = """From 0000000000000000000000000000000000000000 Mon Sep 17 00:00:00 2001
From: Mesh-LLM CI <ci@mesh-llm.local>
Date: Thu, 1 Jan 1970 00:00:00 +0000
Subject: [PATCH] {subject}

Generated by tools/skippy-stage-rewriter from compiler-proven builder
shapes. Auxiliary sidecars and whole-model multi-domain graphs are proven
separately and remain outside the primary decoder stage interval.

---
"""

GENERATOR_VERSION = "0.3.0"
DIFF_HEADER = re.compile(r"^diff --git a/(src/models/[^ ]+) b/[^\n]+$", re.MULTILINE)


def run(command: list[str], *, cwd: Path, capture: bool = False) -> str:
    result = subprocess.run(
        command,
        cwd=cwd,
        check=True,
        text=True,
        stdout=subprocess.PIPE if capture else None,
    )
    return result.stdout if capture else ""


def git(root: Path, *args: str, capture: bool = False) -> str:
    return run(["git", *args], cwd=root, capture=capture)


def invoke_rewriter(
    *,
    rewriter: Path,
    source_root: Path,
    build_dir: Path,
    report: Path,
    llama_commit: str,
    extra_args: list[str],
    apply: bool,
) -> None:
    sources = sorted((source_root / "src/models").glob("*.cpp"))
    if not sources:
        raise RuntimeError(f"no model sources found under {source_root}")
    command = [
        str(rewriter),
        "--source-root",
        str(source_root),
        "--llama-commit",
        llama_commit,
        "--report",
        str(report),
        "-p",
        str(build_dir),
    ]
    if apply:
        command.append("--apply")
    for argument in extra_args:
        command.extend(("--extra-arg", argument))
    command.extend(str(source) for source in sources)
    run(command, cwd=source_root)


def validate_report(report_path: Path, *, idempotence: bool) -> dict:
    report = json.loads(report_path.read_text(encoding="utf-8"))
    builders = report.get("builders")
    if not isinstance(builders, list) or not builders:
        raise RuntimeError("rewriter emitted no builder records")
    if idempotence:
        remaining = [
            builder.get("file", "<unknown>")
            for builder in builders
            if builder.get("verdict") == "transformable"
        ]
        if remaining:
            raise RuntimeError(
                "second rewriter pass still has edits for: "
                + ", ".join(remaining[:10])
            )
    return report


def patch_text(subject: str, diff: str) -> str:
    return PATCH_HEADER.format(subject=subject) + diff + "-- \n2.54.0\n\n"


def load_family_map(path: Path) -> dict[str, list[str]]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if payload.get("schema_version") != 1 or not isinstance(payload.get("families"), dict):
        raise RuntimeError("family source map must use schema_version 1 with a families object")
    result: dict[str, list[str]] = {}
    for family, sources in sorted(payload["families"].items()):
        if not re.fullmatch(r"[a-z0-9][a-z0-9._-]*", family) or not isinstance(sources, list) or not sources:
            raise RuntimeError(f"invalid family source mapping: {family}")
        normalized = sorted(set(sources))
        if len(normalized) != len(sources) or any(
            not re.fullmatch(r"src/models/[a-zA-Z0-9._-]+\.cpp", source)
            for source in normalized
        ):
            raise RuntimeError(f"invalid or duplicate model source mapping: {family}")
        result[family] = normalized
    return result


def split_model_diff(diff: str) -> dict[str, str]:
    matches = list(DIFF_HEADER.finditer(diff))
    if not matches or matches[0].start() != 0:
        raise RuntimeError("generated model diff has an unexpected format")
    sections: dict[str, str] = {}
    for index, match in enumerate(matches):
        source = match.group(1)
        end = matches[index + 1].start() if index + 1 < len(matches) else len(diff)
        if source in sections:
            raise RuntimeError(f"generated model diff repeats source: {source}")
        sections[source] = diff[match.start():end]
    return sections


def load_certified_families(path: Path) -> set[str]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    models = payload.get("models")
    if not isinstance(models, list):
        raise RuntimeError("family manifest must contain a models array")
    families = {model.get("family") for model in models if isinstance(model, dict)}
    if None in families or len(families) != len(models):
        raise RuntimeError("family manifest contains missing or duplicate family names")
    return families


def write_family_shards(
    diff: str,
    output_dir: Path,
    family_map_path: Path,
    family_manifest_path: Path,
) -> dict:
    family_map = load_family_map(family_map_path)
    certified_families = load_certified_families(family_manifest_path)
    if set(family_map) != certified_families:
        missing = sorted(certified_families - set(family_map))
        extra = sorted(set(family_map) - certified_families)
        raise RuntimeError(
            f"family source map does not exactly cover the certification manifest; missing={missing}, extra={extra}"
        )
    reverse: dict[str, set[str]] = {}
    for family, sources in family_map.items():
        for source in sources:
            reverse.setdefault(source, set()).add(family)

    grouped: dict[tuple[str, ...], dict[str, str]] = {}
    for source, section in split_model_diff(diff).items():
        owners = tuple(sorted(reverse.get(source, set())))
        grouped.setdefault(owners, {})[source] = section

    parent = output_dir.parent
    parent.mkdir(parents=True, exist_ok=True)
    temp = Path(tempfile.mkdtemp(prefix=f".{output_dir.name}-", dir=parent))
    shards: list[dict] = []
    try:
        ordered = sorted(grouped.items(), key=lambda item: (not bool(item[0]), item[0]))
        for index, (families, sections) in enumerate(ordered, 1):
            label = "--".join(families) if families else "unmapped"
            filename = f"{index:04d}-family-{label}.patch"
            shard_diff = "".join(sections[source] for source in sorted(sections))
            content = patch_text(f"skippy: generate {label} stage controls", shard_diff)
            (temp / filename).write_text(content, encoding="utf-8")
            shards.append({
                "file": filename,
                "families": list(families),
                "sources": sorted(sections),
                "sha256": hashlib.sha256(content.encode()).hexdigest(),
            })
        series = {
            "schema_version": 1,
            "generator_version": GENERATOR_VERSION,
            "full_patch_sha256": hashlib.sha256(diff.encode()).hexdigest(),
            "shards": shards,
        }
        (temp / "series.json").write_text(
            json.dumps(series, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        (temp / "series").write_text(
            "".join(f"{shard['file']}\n" for shard in shards), encoding="utf-8"
        )
        if output_dir.exists():
            shutil.rmtree(output_dir)
        temp.rename(output_dir)
        return series
    except Exception:
        shutil.rmtree(temp, ignore_errors=True)
        raise


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", type=Path, required=True)
    parser.add_argument("--build-dir", type=Path, required=True)
    parser.add_argument("--rewriter", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--shard-output-dir", type=Path)
    parser.add_argument("--family-source-map", type=Path)
    parser.add_argument("--family-manifest", type=Path)
    parser.add_argument("--report", type=Path, required=True)
    parser.add_argument(
        "--diff-base",
        default="HEAD",
        help=(
            "git revision used as the patch base; use the pinned upstream "
            "revision to consolidate existing and newly generated model edits"
        ),
    )
    parser.add_argument(
        "--extra-arg",
        action="append",
        default=[],
        help="extra compiler argument forwarded to ClangTool (repeatable)",
    )
    args = parser.parse_args(argv)

    source_root = args.source_root.resolve()
    build_dir = args.build_dir.resolve()
    rewriter = args.rewriter.resolve()
    output = args.output.resolve()
    shard_output_dir = args.shard_output_dir.resolve() if args.shard_output_dir else None
    family_source_map = args.family_source_map.resolve() if args.family_source_map else None
    family_manifest = args.family_manifest.resolve() if args.family_manifest else None
    if len([value for value in (shard_output_dir, family_source_map, family_manifest) if value is not None]) not in (0, 3):
        parser.error("--shard-output-dir, --family-source-map, and --family-manifest must be used together")
    first_report = args.report.resolve()
    second_report = first_report.with_name(first_report.stem + "-second.json")

    try:
        if git(
            source_root,
            "status",
            "--porcelain",
            "--untracked-files=no",
            capture=True,
        ).strip():
            raise RuntimeError("source tree must be clean before generation")

        upstream_marker = source_root / ".mesh-llm-upstream-sha"
        llama_commit = (
            upstream_marker.read_text(encoding="utf-8").strip()
            if upstream_marker.exists()
            else git(source_root, "rev-parse", "HEAD", capture=True).strip()
        )

        first_report.parent.mkdir(parents=True, exist_ok=True)
        invoke_rewriter(
            rewriter=rewriter,
            source_root=source_root,
            build_dir=build_dir,
            report=first_report,
            llama_commit=llama_commit,
            extra_args=args.extra_arg,
            apply=True,
        )
        first = validate_report(first_report, idempotence=False)

        invoke_rewriter(
            rewriter=rewriter,
            source_root=source_root,
            build_dir=build_dir,
            report=second_report,
            llama_commit=llama_commit,
            extra_args=args.extra_arg,
            apply=False,
        )
        second = validate_report(second_report, idempotence=True)

        diff = git(
            source_root,
            "diff",
            "--no-ext-diff",
            "--binary",
            "--full-index",
            args.diff_base,
            "--",
            "src/models",
            capture=True,
        )
        if not diff:
            raise RuntimeError("generation produced an empty model patch")

        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(
            patch_text("skippy: generate model-family stage controls", diff),
            encoding="utf-8",
        )
        series = (
            write_family_shards(diff, shard_output_dir, family_source_map, family_manifest)
            if shard_output_dir is not None and family_source_map is not None and family_manifest is not None
            else None
        )
        print(
            json.dumps(
                {
                    "output": str(output),
                    "first_summary": first.get("summary", {}),
                    "second_summary": second.get("summary", {}),
                    "shards": len(series["shards"]) if series else 0,
                },
                sort_keys=True,
            )
        )
        return 0
    except (OSError, RuntimeError, subprocess.CalledProcessError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
