#!/usr/bin/env python3
"""Generate the deterministic llama.cpp model-family stage-control patch."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess
import sys


PATCH_HEADER = """From 0000000000000000000000000000000000000000 Mon Sep 17 00:00:00 2001
From: Mesh-LLM CI <ci@mesh-llm.local>
Date: Thu, 1 Jan 1970 00:00:00 +0000
Subject: [PATCH] skippy: generate model-family stage controls

Generated by tools/skippy-stage-rewriter from compiler-proven builder
shapes. Irregular builders remain unchanged and carry structured refusal
reasons in the generation report.

---
"""


def run(command: list[str], *, cwd: Path, capture: bool = False) -> str:
    result = subprocess.run(
        command,
        cwd=cwd,
        check=True,
        text=True,
        stdout=subprocess.PIPE if capture else None,
    )
    return result.stdout if capture else ""


def git(root: Path, *args: str, capture: bool = False) -> str:
    return run(["git", *args], cwd=root, capture=capture)


def invoke_rewriter(
    *,
    rewriter: Path,
    source_root: Path,
    build_dir: Path,
    report: Path,
    llama_commit: str,
    extra_args: list[str],
    apply: bool,
) -> None:
    sources = sorted((source_root / "src/models").glob("*.cpp"))
    if not sources:
        raise RuntimeError(f"no model sources found under {source_root}")
    command = [
        str(rewriter),
        "--source-root",
        str(source_root),
        "--llama-commit",
        llama_commit,
        "--report",
        str(report),
        "-p",
        str(build_dir),
    ]
    if apply:
        command.append("--apply")
    for argument in extra_args:
        command.extend(("--extra-arg", argument))
    command.extend(str(source) for source in sources)
    run(command, cwd=source_root)


def validate_report(report_path: Path, *, idempotence: bool) -> dict:
    report = json.loads(report_path.read_text(encoding="utf-8"))
    builders = report.get("builders")
    if not isinstance(builders, list) or not builders:
        raise RuntimeError("rewriter emitted no builder records")
    if idempotence:
        remaining = [
            builder.get("file", "<unknown>")
            for builder in builders
            if builder.get("verdict") == "transformable"
        ]
        if remaining:
            raise RuntimeError(
                "second rewriter pass still has edits for: "
                + ", ".join(remaining[:10])
            )
    elif not any(builder.get("verdict") == "transformable" for builder in builders):
        raise RuntimeError("first rewriter pass produced no edits")
    return report


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", type=Path, required=True)
    parser.add_argument("--build-dir", type=Path, required=True)
    parser.add_argument("--rewriter", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--report", type=Path, required=True)
    parser.add_argument(
        "--extra-arg",
        action="append",
        default=[],
        help="extra compiler argument forwarded to ClangTool (repeatable)",
    )
    args = parser.parse_args(argv)

    source_root = args.source_root.resolve()
    build_dir = args.build_dir.resolve()
    rewriter = args.rewriter.resolve()
    output = args.output.resolve()
    first_report = args.report.resolve()
    second_report = first_report.with_name(first_report.stem + "-second.json")

    try:
        if git(
            source_root,
            "status",
            "--porcelain",
            "--untracked-files=no",
            capture=True,
        ).strip():
            raise RuntimeError("source tree must be clean before generation")

        upstream_marker = source_root / ".mesh-llm-upstream-sha"
        llama_commit = (
            upstream_marker.read_text(encoding="utf-8").strip()
            if upstream_marker.exists()
            else git(source_root, "rev-parse", "HEAD", capture=True).strip()
        )

        first_report.parent.mkdir(parents=True, exist_ok=True)
        invoke_rewriter(
            rewriter=rewriter,
            source_root=source_root,
            build_dir=build_dir,
            report=first_report,
            llama_commit=llama_commit,
            extra_args=args.extra_arg,
            apply=True,
        )
        first = validate_report(first_report, idempotence=False)

        invoke_rewriter(
            rewriter=rewriter,
            source_root=source_root,
            build_dir=build_dir,
            report=second_report,
            llama_commit=llama_commit,
            extra_args=args.extra_arg,
            apply=False,
        )
        second = validate_report(second_report, idempotence=True)

        diff = git(
            source_root,
            "diff",
            "--no-ext-diff",
            "--binary",
            "--full-index",
            "HEAD",
            "--",
            "src/models",
            capture=True,
        )
        if not diff:
            raise RuntimeError("generation produced an empty model patch")

        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(PATCH_HEADER + diff + "-- \n2.54.0\n\n", encoding="utf-8")
        print(
            json.dumps(
                {
                    "output": str(output),
                    "first_summary": first.get("summary", {}),
                    "second_summary": second.get("summary", {}),
                },
                sort_keys=True,
            )
        )
        return 0
    except (OSError, RuntimeError, subprocess.CalledProcessError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
